### ISSUE TITLE
Add ability to supply conversion type as string arg

### ISSUE THREAD

**Issue by blacktop** [spf13/cast#151]
I'm using yaml to define Go structs so:
```yaml
args:
  - name: Field1
     type: uint64
     value: 32
  - name: Field2
     type: uint32
     value: 200
```
```go
type Field struct {
	Name  string
	Type  string
	Value any
}
```

So when I unmarshal I want to write that struct to a []byte

So it'd be awesome if I could use `cast` to do:
```go
for _, arg := range args {
    for _, field := range arg {
        val := cast.Convert(type, value)
        binary.Write(r, binary.LittleEndian, &val)
     }
}
